"""empty message

Revision ID: 46c92098d8fe
Revises: e8c4bd462c37
Create Date: 2019-09-11 10:27:23.492899

"""

# revision identifiers, used by Alembic.
revision = '46c92098d8fe'
down_revision = 'e8c4bd462c37'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('available_sailings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('departure_time', sa.String(), nullable=False),
    sa.Column('arrival_time', sa.String(), nullable=False),
    sa.Column('departure_terminal', sa.String(), nullable=False),
    sa.Column('arrival_terminal', sa.String(), nullable=False),
    sa.Column('vessel_name', sa.String(), nullable=False),
    sa.Column('reservations_available', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('route', sa.String(length=80), nullable=False),
    sa.Column('dates', sa.String(length=100), nullable=False),
    sa.Column('result_all', postgresql.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('results')
    op.drop_table('available_sailings')
    ### end Alembic commands ###
