"""empty message

Revision ID: 86e886177a63
Revises: f1b58e87eada
Create Date: 2019-09-10 16:00:27.210334

"""

# revision identifiers, used by Alembic.
revision = '86e886177a63'
down_revision = 'f1b58e87eada'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('results')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('results',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('route', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('dates', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('result_all', postgresql.JSON(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=u'results_pkey')
    )
    ### end Alembic commands ###
