"""empty message

Revision ID: e8c4bd462c37
Revises: 63f5a8c75f55
Create Date: 2019-09-10 16:41:16.494290

"""

# revision identifiers, used by Alembic.
revision = 'e8c4bd462c37'
down_revision = '63f5a8c75f55'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('results')
    op.drop_table('sailings')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sailings',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('departure_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('arrival_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('departure_terminal', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('arrival_terminal', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('vessel_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('reservations_available', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=u'sailings_pkey')
    )
    op.create_table('results',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('route', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('dates', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('result_all', postgresql.JSON(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=u'results_pkey')
    )
    ### end Alembic commands ###
