"""empty message

Revision ID: f1b58e87eada
Revises: None
Create Date: 2019-09-09 13:21:30.815044

"""

# revision identifiers, used by Alembic.
revision = 'f1b58e87eada'
down_revision = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('route', sa.String(length=80), nullable=False),
    sa.Column('dates', sa.String(length=100), nullable=False),
    sa.Column('result_all', postgresql.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('results')
    ### end Alembic commands ###
